In [5]:
import numpy as np

In [2]:
pole_1d = np.array([0, 5, 10, 15, 20])
print(pole_1d)
pole_2d = np.array([[1.0, 3, 5, 7],
                    [2, 4, 6, 8]])
print(pole_2d)
pole_3d =np.array([[[1,1],[2,2]],
                   [[3,3],[4,4]],
                   [[5,5],[6,6]]])
print(pole_3d)

[ 0  5 10 15 20]
[[1. 3. 5. 7.]
 [2. 4. 6. 8.]]
[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]]


In [3]:
pole_1d

array([ 0,  5, 10, 15, 20])

In [69]:
print("Broj na elementi:",pole_2d.size)
print("Broj na dimenzii:",pole_2d.ndim)
print("Elementi po dimenzija:",pole_2d.shape)
print("Golemina vo bajti:",pole_2d.nbytes)
print("Tip na podatoci:",pole_2d.dtype)

Broj na elementi: 8
Broj na dimenzii: 2
Elementi po dimenzija: (2, 4)
Golemina vo bajti: 64
Tip na podatoci: float64


In [40]:
pole_1d = np.array([0, 5], dtype='S3')
print(pole_1d.dtype)
pole_2d = np.array([[1.0, 3], [2, 4]], dtype = np.int64)
print(pole_2d.dtype)

|S3
int64


In [41]:
pole_1d_int = pole_2d.astype(np.int32)
print(pole_1d_int.dtype)
pole_2d_float=pole_2d.astype('f')
print(pole_2d_float.dtype)


int32
float32


In [54]:
# 1D niza od 4 nuli 
nuli = np.zeros(4)
print(nuli)


[0. 0. 0. 0.]


In [55]:
# 2x3 niza od edinici od tipot int16 
edinici = np.ones((2,3), dtype=np.int16)
print(edinici)


[[1 1 1]
 [1 1 1]]


In [56]:
# 2x2 niza od vrednosti 2 
dvojki = np.full((2, 2),2)
print(dvojki)


[[2 2]
 [2 2]]


In [57]:
# 2x2 niza od nuli so edinici na glavanta dijagonala
identitet = np.identity(2, dtype='i')
print(identitet)


[[1 0]
 [0 1]]


In [58]:
rastechka = np.arange(0,12,3)
print(rastechka)

[0 3 6 9]


In [67]:
# 2x3 niza od slucjani broevi vo opseg 0 do 1
sluchajni=np.random.random(size=(2,3))
print(sluchajni)
# 2x5 niza od celi slucjani broevi vo opseg 10 do 20
sluchajni_celi = np.random.randint(10,20, size=(2,5))
print(sluchajni_celi)
# 1D niza od slucjani broevi so normalna raspredelba
# so sr. vred. 0 i std. dev. 2
slucjani_normalna = np.random.normal(0,4,6)
print(slucjani_normalna)


[[0.26103367 0.68712668 0.15238305]
 [0.06393533 0.68933313 0.53652774]]
[[19 14 13 12 14]
 [12 16 15 11 13]]
[ 4.57614827  3.94573143  0.10806118  6.74270484  4.55702101 -2.6323091 ]


Пристап до податоци

In [3]:
pole_1d=np.array([2, 4, 6, 8, 10, 12, 14])
print(pole_1d[2])
print(pole_1d[1:5:3])
print(pole_1d[::-2])

6
[ 4 10]
[14 10  6  2]


In [4]:
pole_2d=np.array([[0, 10, 20, 30, 40],
                  [50, 60, 70, 80, 90],
                  [100, 110, 120, 130, 140],
                  [150, 160, 170, 180, 190]])
print(pole_2d[1,2])  # element od redica 1 i kolona 2
print(pole_2d[1:3,1:4]) # site elementi od redica 1 do 2 i kolona 1 do 3
print(pole_2d[1:,1:4:2]) # site elementi od redica 1 do kraj i sekoj vtor od kolona 1 do 3 
print(pole_2d[2:,:4]) # site elementi od redica 2 do rkaj i od prva kolona do kolona 3
print(pole_2d[::2,:]) # site elementi od sekoja vtora redica od site koloni
print(pole_2d[:,-1]) # site elementi od poslednata kolona 

70
[[ 60  70  80]
 [110 120 130]]
[[ 60  80]
 [110 130]
 [160 180]]
[[100 110 120 130]
 [150 160 170 180]]
[[  0  10  20  30  40]
 [100 110 120 130 140]]
[ 40  90 140 190]


Филтрирање

In [10]:
print("Pole:",pole_1d)
dellivi_so_4 = (pole_1d % 4 == 0) # True ako elementot e delliv so 4
print("Maska:",dellivi_so_4)
print("Pole[maska]:",pole_1d[dellivi_so_4])

Pole: [ 2  4  6  8 10 12 14]
Maska: [False  True False  True False  True False]
Pole[maska]: [ 4  8 12]


In [22]:
# pechatenje na broevi koi ne se dellivi so 4
print(pole_1d[pole_1d % 4 > 0])

[ 2  6 10 14]


In [60]:
denovi=np.array(["Ponedelnik","Vtornik","Sreda","Chetvrtok","Petok","Sabota","Nedela"])
temperaturi=np.array([[17, 19, 15, 10, 21, 22, 12],
                      [27, 31, 29, 28, 35, 36, 30]])
print(temperaturi[:, (denovi=="Vtornik") | (denovi=="Chetvrtok")])

[[19 10]
 [31 28]]


In [65]:
niski_temperaturi = temperaturi < 20
print("2D maska:\n",niski_temperaturi)
print("1D rezultat:\n",temperaturi[niski_temperaturi])

2D maska:
 [[ True  True  True  True False False  True]
 [False False False False False False False]]
1D rezultat:
 [17 19 15 10 12]


In [15]:
denovi=="Vtornik"

array([False,  True, False, False, False, False, False])

Низи од индекси

In [67]:
print(pole_1d[[6, 1, 4]]) # elementi so indeks 6, 1 i 4
print(pole_2d[[3, 1]])    # elementi od red so indeks 3 i 1



[14  4 10]
[[150 160 170 180 190]
 [ 50  60  70  80  90]]
[90 70]


Комбиниран пристап

In [7]:
print(pole_2d[1, [4, 2, 1]])    # elementi od red 1 i koloni 4 i 2
print(pole_2d[[1,0], 1::2])    # elementi od red 1 i 0 i sekoja vtora kolona pocnjvajki od kolona 1

[90 70 60]
[[60 80]
 [10 30]]


In [68]:
print(pole_2d[[0, 2, 1], [3, 1, 4]]) # element so koordinati (0,3), (2,1) и (1,4)


[ 30 110  90]


In [8]:
selektirani_redici=pole_2d[[0, 2, 1]]
print(selektirani_redici[:,[3, 1, 4]])



[[ 30  10  40]
 [130 110 140]
 [ 80  60  90]]


In [9]:
print(pole_2d[[0, 2, 1]][:,[3, 1, 4]]) # matrica so red 0, 2, 1 i kolona 3, 1, 4

[[ 30  10  40]
 [130 110 140]
 [ 80  60  90]]


Промена на вредности

In [3]:
pole_2d=np.random.randint(0,10,size=(3,4))
pole_2d[0,0] = 1
print(pole_2d)


[[1 5 3 1]
 [3 4 1 8]
 [8 7 9 9]]


In [4]:
pole_2d[:,0] = 2 #site elementi na kolona 0 dobivaat vrednost 2
pole_2d[:,1] = [1,2,3] #elementite na kolona 1 dobivaat vrednost 1, 2 i 3, soodvetno
print(pole_2d)

[[2 1 3 1]
 [2 2 1 8]
 [2 3 9 9]]


In [34]:

pole_2d[1,2:] = 3 #site elementi na red 1, pochnuvajki od kolona 2 dobivaat vrednost 3
pole_2d[2,:] = [10, 20, 30, 40]  #elementite na red 2 dobivaat vrednost 10, 20, 30 i 40, soodvetno
print(pole_2d)


[[ 2  1  0  4]
 [ 2  2  3  3]
 [10 20 30 40]]


In [35]:
pole_2d[pole_2d==2]=22
print(pole_2d)

[[22  1  0  4]
 [22 22  3  3]
 [10 20 30 40]]


Погледи и копии

In [53]:
pole_2d = np.array([[0, 10, 20, 30],
                  [40, 50, 60, 70],
                  [80, 90, 100, 110]])
opseg=pole_2d[1,:] # opseg e pogled sostaven od elementite na red 1
opseg[:] = 33 # promenata na elementite na opseg se afektira vo pole_2d
print("Opseg:\n",opseg)
print("Originalna niza:\n",pole_2d)


Opseg:
 [33 33 33 33]
Originalna niza:
 [[  0  10  20  30]
 [ 33  33  33  33]
 [ 80  90 100 110]]


In [54]:
pole_2d=np.array([[0, 10, 20, 30],
                  [40, 50, 60, 70],
                  [80, 90, 100, 110]])
opseg=pole_2d[1,:].copy() # opseg e kopja od elementite na red 1
opseg[:]=33 # promenata na elementite na opseg NE se afektira vo pole_2d
print("Opseg:\n",opseg)
print("Originalna niza:\n",pole_2d)

Opseg:
 [33 33 33 33]
Originalna niza:
 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


Промена на димензии

In [5]:
rastechka_2d = np.arange(15).reshape(3,5)
print(rastechka_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
print(rastechka_2d.reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [10]:
pole_nepoznata_dim=np.arange(18).reshape(2,3,-1)
print("Pole:\n", pole_nepoznata_dim)
print("Elementi po dimenzija:\n", pole_nepoznata_dim.shape)



Pole:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Elementi po dimenzija:
 (2, 3, 3)


In [11]:
print(rastechka_2d.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Спојување и разделување

In [27]:
pole1 = np.array([[1, 2],
                  [3, 4]])
pole2 = np.array([[10, 20], 
                  [30, 40]])
print("Spojuvanje po oska 0:\n",np.concatenate((pole1, pole2))) # axis=0
print("Spojuvanje po oska 1:\n",np.concatenate((pole1, pole2), axis=1))

Spojuvanje po oska 0:
 [[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]


In [25]:
print("Spojuvanje po oska 0:\n",np.stack((pole1, pole2)))
print("Spojuvanje po oska 1:\n",np.stack((pole1, pole2), axis=1))

Spojuvanje po oska 0:
 [[[ 1  2]
  [ 3  4]]

 [[10 20]
  [30 40]]]
Spojuvanje po oska 1:
 [[[ 1  2]
  [10 20]]

 [[ 3  4]
  [30 40]]]


In [31]:
print("Spojuvanje po oska 0:\n",np.dstack((pole1, pole2)))
print("Spojuvanje po oska 1:\n",np.hstack((pole1, pole2)))
print("Spojuvanje po oska 1:\n",np.hstack((pole1, pole2)))
print(np.vstack((pole1, pole2)).shape)
print(np.hstack((pole1, pole2)).shape)

Spojuvanje po oska 0:
 [[[ 1 10]
  [ 2 20]]

 [[ 3 30]
  [ 4 40]]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
(4, 2)
(2, 4)


In [53]:
pole_2d=np.arange(1,13).reshape(3,4)
print("Originalna niza:\n",pole_2d)
razdeleno_pole=np.split(pole_2d,2, axis=1) # razdeli po koloni
print("Prva niza:\n",razdeleno_pole[0])
print("Vtora niza:\n",razdeleno_pole[1])

Originalna niza:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Prva niza:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Vtora niza:
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [54]:
# razdeli po redici, axis=0, razdeli od redica 1
razdeleno_pole=np.split(pole_2d, [1]) 
print("Prva niza:\n",razdeleno_pole[0])
print("Vtora niza:\n",razdeleno_pole[1])

Prva niza:
 [[1 2 3 4]]
Vtora niza:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
razdeleno_pole=np.vsplit(pole_2d, [2]) 
print("Prva niza vsplit:\n",razdeleno_pole[0])
print("Vtora niza vsplit:\n",razdeleno_pole[1])
razdeleno_pole=np.hsplit(pole_2d, 2) 
print("Prva niza hsplit:\n",razdeleno_pole[0])
print("Vtora niza hsplit:\n",razdeleno_pole[1])

Prva niza vsplit:
 [[1 2 3 4]
 [5 6 7 8]]
Vtora niza vsplit:
 [[ 9 10 11 12]]
Prva niza hsplit:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Vtora niza hsplit:
 [[ 3  4]
 [ 7  8]
 [11 12]]


Пребарување

In [4]:
pole_2d=np.arange(1,13).reshape(3,4)
print(np.where(pole_2d %3 == 0))


(array([0, 1, 2, 2]), array([2, 1, 0, 3]))


In [77]:
print(pole_2d[pole_2d % 3 == 0])

[ 3  6  9 12]


In [76]:
print(np.where(pole_2d %3 == 0, pole_2d, 0))

[[ 0  0  3  0]
 [ 0  6  0  0]
 [ 9  0  0 12]]


Подредување

In [90]:
pole=np.random.randint(10,size=(3,4))
print("Originalna niza:\n",pole)
print("Podreduvanje po dimenzija 1:\n",np.sort(pole))
print("Podreduvanje po dimenzija 0:\n",np.sort(pole, axis=0))
print("Podreduvanje na izramneta niza:\n",np.sort(pole, axis=None))

Originalna niza:
 [[2 7 3 7]
 [8 8 8 2]
 [3 0 2 4]]
Podreduvanje po dimenzija 1:
 [[2 3 7 7]
 [2 8 8 8]
 [0 2 3 4]]
Podreduvanje po dimenzija 0:
 [[2 0 2 2]
 [3 7 3 4]
 [8 8 8 7]]
Podreduvanje na izramneta niza:
 [0 2 2 2 3 3 4 7 7 8 8 8]


Аритметика

In [3]:
a = np.array([[4, 5, 6],
              [3, 2, 1]])
b = np.array([[7, 8, 9],
              [6, 5, 4]])

print("a + b =\n", a + b)
print("1 / a =\n", 1 / a)
print("b ** 2 + 1=\n", b ** 2 + 1)



a + b =
 [[11 13 15]
 [ 9  7  5]]
1 / a =
 [[0.25       0.2        0.16666667]
 [0.33333333 0.5        1.        ]]
b ** 2 + 1=
 [[50 65 82]
 [37 26 17]]


In [6]:
A = np.array([[4, 5, 6],
              [3, 2, 1],
              [1, 2, 3]])
print("A*A (mnozhenje na matrici):\n", A.dot(A))


A*A (mnozhenje na matrici):
 [[37 42 47]
 [19 21 23]
 [13 15 17]]


In [11]:
c=np.array([2, 2, 2])
print(a+c)
print(a+c.T)

[[6 7 8]
 [5 4 3]]
[[6 7 8]
 [5 4 3]]


Емитување 

In [21]:
A= np.array([[1, 2, 3],
             [4, 5, 6]])
B=np.array([10])
print(A.shape)
print(B.shape)

(2, 3)
(1,)


In [23]:
print("A+B\n",A+B)

A+B
 [[11 12 13]
 [14 15 16]]


In [29]:
A= np.array([[1, 2, 3],
             [4, 5, 6]])
B=np.array([10, 11, 12])
print(A.shape)
print(B.shape)

(2, 3)
(3,)


In [30]:
print("A+B\n",A+B)

A+B
 [[11 13 15]
 [14 16 18]]


In [31]:
A= np.array([[1, 2, 3],
             [4, 5, 6]])
B=np.array([10, 11])
print(A.shape)
print(B.shape)

(2, 3)
(2,)


In [32]:
print("A+B\n",A+B)

ValueError: ignored

In [6]:
A = np.array([[4, 5, 6],
              [3, 2, 1],
              [1, 2, 3]])
print("A*A (mnozhenje na matrici):\n", A.dot(A))


A*A (mnozhenje na matrici):
 [[37 42 47]
 [19 21 23]
 [13 15 17]]


In [7]:
A.transpose()

array([[4, 3, 1],
       [5, 2, 2],
       [6, 1, 3]])

Математички функции

In [45]:
a=10*np.random.random(size=(1,4))
print("Niza:\n",a)
cel_del,frakcija = np.modf(a)
print("Cel del:\n",cel_del)
print("Frakcija:\n",frakcija)

Niza:
 [[4.24412867 2.26933936 9.21886136 1.36463729]]
Cel del:
 [[0.24412867 0.26933936 0.21886136 0.36463729]]
Frakcija:
 [[4. 2. 9. 1.]]


In [65]:
z = np.array([[3, 6, 1],
             [4, 9, 5]])
print("Min i max na cela niza:\n",np.min(z), np.max(z))
print("Min i max po oska 1:\n",np.min(z,axis=1), np.max(z,axis=1))
print("Indeksi na min i max po oska 1:\n",np.argmin(z,axis=1), np.argmax(z,axis=1))


Min i max na cela niza:
 1 9
Min i max po oska 1:
 [1 4] [6 9]
Indeksi na min i max po oska 1:
 [2 0] [1 1]


In [66]:
print("Suma na cela niza:\n",z.sum())
print("Suma po oska 0:\n",z.sum(axis=0))
print("Kumulativna suma:\n",z.cumsum())
print("Kumulativna suma po oska 1:\n",z.cumsum(axis=1))


Suma na cela niza:
 28
Suma po oska 0:
 [ 7 15  6]
Kumulativna suma:
 [ 3  9 10 14 23 28]
Kumulativna suma po oska 1:
 [[ 3  9 10]
 [ 4 13 18]]
